name: Generate Snake Animation

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Manual run message'
        required: false
        default: 'Manual trigger to generate snake animation'
  schedule:
  - cron: "0 */12 * * *" # Fallback automated run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Platane/snk@master
      id: snake-gif
      with:
        github_user_name: puskartrital
        gif_out_path: dist/github-contribution-grid-snake.svg
        svg_out_path: dist/github-contribution-grid-snake.svg

    - uses: crazy-max/ghaction-github-pages@v2.1.3
      with:
        target_branch: output
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
